### ISSUE TITLE
Question about rmeasure and dmeasure.

### ISSUE THREAD

**Issue by LUOSDU** [kingaa/kingaa.github.io#1]
Thank you at the beginning!
The measurement model is defined according to different distribution. However, I find it is very interesting that the  negative binomial model could not fit for all the data and sometime I need to replace the NB model with binomial model or Poisson model. Is there any golden standard for me to pick up the 	
appropriate measurement model during the analysis?

**Comment by kingaa** [comment]
Alas, there is no gold standard and, sad to say, there is no magic. The measurement model is as much a part of the model as the latent process model. Accordingly, the choice of the measurement model is governed by the same considerations: Which model fits the data best? Which model has the greater predictive power?

Nor is the choice of the measurement model without consequences for the choice of the latent process model. Despite the fact that one typically is much more interested in the latent process than in the measurement, if one does not pay careful attention to both, one risks making incorrect or suboptimal inference.

**Comment by kingaa** [comment]
Use the **pomp** issues page: https://github.com/kingaa/pomp/issues
